[build]
  publish = "build"
  command = "npm run build && npm run test && npm run postbuild"

[context.production]
  command = "npm run build:prod && npm run test && npm run postbuild"

[context.deploy-preview]
  command = "npm run build:dev && npm run test && npm run postbuild"
  environment = { REACT_APP_API_KEY="f444a77f642f0982dbc23fda35d86cf6" }

[[plugins]]
  package = "./netlify-plugin-cypress"