[build]
  publish = "build"
  command = "npm run build && npm run test && npm run postbuild"

[context.production]
  command = "npm run build && npm run test && npm run postbuild"

[context.deploy-preview]
  command = "npm run build"
  
